### ISSUE TITLE
Setup PyFlakes (or Flake8) and JSHint (or ESLint) (Bugfinding)

### ISSUE THREAD

**Issue by jkim10** [MattKersey/DjangoUnchained#4]

**Comment by MattKersey** [comment]
Considering changing from PyFlakes to Flake8 as it integrates with VS Code.

**Comment by jkim10** [comment]
> Considering changing from PyFlakes to Flake8 as it integrates with VS Code.

Wait, isn't PyFlakes and Flake8 a linter? I thought we need a bug finder, like PyChecker

**Comment by MattKersey** [comment]
After doing some more research, I have found that JSHint does not play well with React because React uses JSX and not pure JS. Supposedly there exist(s/ed) a JSHint 3 that is set up to work with React, but I can not find any mention of it outside of Stack Overflow. Most people suggest using ESLint instead. This would cover both linting and bug-finding. We may be able to simplify our toolchain by removing both JSHint and StandardJS and replacing them with ESLint. @jkim10 @ceguiluzrosas @yiqiao-liu  would this be alright with you?

**Comment by yiqiao-liu** [comment]
> After doing some more research, I have found that JSHint does not play well with React because React uses JSX and not pure JS. Supposedly there exist(s/ed) a JSHint 3 that is set up to work with React, but I can not find any mention of it outside of Stack Overflow. Most people suggest using ESLint instead. This would cover both linting and bug-finding. We may be able to simplify our toolchain by removing both JSHint and StandardJS and replacing them with ESLint. @jkim10 @ceguiluzrosas @yiqiao-liu would this be alright with you?

I never used any of these but the replacement sounds ok to me

**Comment by ceguiluzrosas** [comment]
Same ^^^ I can update the workflow if we're all good 👍

**Comment by ceguiluzrosas** [comment]
@MattKersey I ran these eslint-commands and I got it to work, but I'm not sure of whether I should commit the `package.json` file. 
```bash
cd frontend
 ./node_modules/.bin/eslint --init
# answer a bunch of questions
eslint src --fix
# linting errors are reported which is good since they prove that eslint works
```
These were my responses to the questions after running `.../eslint --init`
```
✔ How would you like to use ESLint? · style (super combo - last option)
✔ What type of modules does your project use? · esm (import/export)
✔ Which framework does your project use? · react
✔ Does your project use TypeScript? · No
✔ Where does your code run? · node
✔ How would you like to define a style for your project? · guide (popular guide)
✔ Which style guide do you want to follow? · standard
✔ What format do you want your config file to be in? · JSON
```
